### 查询课程列表
POST {{gateway_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmciXSwidXNlcl9uYW1lIjoie1wiY29tcGFueUlkXCI6XCIxMjMyMTQxNDI1XCIsXCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4VDA4OjMyOjAzXCIsXCJpZFwiOlwiNTJcIixcIm5hbWVcIjpcIk3ogIHluIhcIixcInNleFwiOlwiMVwiLFwic3RhdHVzXCI6XCJcIixcInVzZXJuYW1lXCI6XCJ0MVwiLFwidXR5cGVcIjpcIjEwMTAwMlwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2OTA0ODU1MzMsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiOTQ4OGM0NWUtNTdmMi00OGY2LTgwMWQtOGJiMWU4M2M0ODcxIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.ctJh5Q-mztUmixp7NUtbkllndwcDqDV2CjJgXB-iEGU

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": "203001"
}


### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "201000",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "",
  "grade": "204001",
  "description": ""
}

### 根据课程id查询课程信息
GET {{gateway_host}}/content/course/40
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmciXSwidXNlcl9uYW1lIjoie1wiY29tcGFueUlkXCI6XCIxMjMyMTQxNDI1XCIsXCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4VDA4OjMyOjAzXCIsXCJpZFwiOlwiNTJcIixcIm5hbWVcIjpcIk3ogIHluIhcIixcInNleFwiOlwiMVwiLFwic3RhdHVzXCI6XCJcIixcInVzZXJuYW1lXCI6XCJ0MVwiLFwidXR5cGVcIjpcIjEwMTAwMlwifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2OTA0ODU1MzMsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiOTQ4OGM0NWUtNTdmMi00OGY2LTgwMWQtOGJiMWU4M2M0ODcxIiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.ctJh5Q-mztUmixp7NUtbkllndwcDqDV2CjJgXB-iEGU

### 查询某个课程的课程计划

GET {{content_host}}/content/teachplan/74/tree-nodes


